credentials:
  usernames:
    carlos_ochoa:
      email: "carlosj.ochoa@correo.policia.gov.co"
      name: "cjop1"
      password: "$2b$12$XWQ8GMtR4y2kDBrw8Aix0eeb.TyTxeYsiThyYwbRyWEC5Bd9/6qdy" # Hash bcrypt para At3usSipqr2s0
    alexander_obando:
      email: "alexander.obando@correo.policia.gov.co"
      name: "Director de Sanidad"
      password: "$2b$12$JFPZ5U3raEAm2d6yvCX8uOPg8HqiNBbW3iP8DFlE7z9teJnoq14vK" # Hash bcrypt para Faro6!Pez9Ma
    hellen_jimenez:
      email: "hellen.jimenez@correo.policia.gov.co"
      name: "jefeAteus"
      password: "$2b$12$i1iDoHKybOe5yrQkc7fEDOxfqJBWWivq3PCjy3dMzR6ECUspWc2se" # Hash bcrypt para At3usSipqr2s2
    paula_giraldo:
      email: "paula.giraldo@correo.policia.gov.co"
      name: "Responsable SIPQR2S"
      password: "$2b$12$2lkuqvs3yHAGHhD3iAhPV.gqi/RDvv/Y2FPH.UQOkVYSMwXyXulZ6" # Hash bcrypt para At3usSipqr2s3
    luis_burgos:
      email: "luis.burgos@correo.policia.gov.co"
      name: "Subdirector Sanidad"
      password: "$2b$12$Jb6pq8fJvkVMco/P3KYBj.Sn6uaTQ0IRzbL86FVJNqa027P1TSsES" # Hash bcrypt para Faro7!Pez9Ma
    rases_1:
      email: "xxxxxxx@correo.policia.gov.co"
      name: "RASES_1"
      password: "$2b$12$OTU23pi0AKZMDtB2O8skS.jGp41yT6fkupC3TWN71/OEKMyyr92Wa" # Hash bcrypt para '5n3ONS6oH0D8'
    rases_2:
      email: "xxxxxxx@correo.policia.gov.co"
      name: "RASES_2"
      password: "$2b$12$MOUqSzLTZC0g8nTLmqMcl.hicW6VjlEtTIIq4I7AeuMoCHqXcqgKy" # Hash bcrypt para 'd2f8kV566h4M'
    rases_3:
      email: "xxxxxxx@correo.policia.gov.co"
      name: "RASES_3"
      password: "$2b$12$AhJpmNXNcpKeUDFLINXpV.RxkbuBBjFXvvgNPzuKx3ic3h2veB1qS" # Hash bcrypt para '8ZUQD93rvyt4'
    rases_4:
      email: "xxxxxxx@correo.policia.gov.co"
      name: "RASES_4"
      password: "$2b$12$hRDb4ayrZF61E1t9UTmbwehoLWPp538IkQLO2E9AG2VONTKOpkwnK" # Hash bcrypt para '7VsOn07554NP'
    rases_5:
      email: "xxxxxxx@correo.policia.gov.co"
      name: "RASES_5"
      password: "$2b$12$XsENVbEFXeUB45naAu2/yuZ4UGRlhOkwnGsFCz/dpCIqSPGbQTUP2" # Hash bcrypt para '50J6CI7uVVyb'
    rases_6:
      email: "xxxxxxx@correo.policia.gov.co"
      name: "RASES_6"
      password: "$2b$12$VqGWoSLJptUFPwfbtE/PA.9QPApbtRNiHYsS.WfQWdNJg7E/ZX9Hi" # Hash bcrypt para 'Hkg0c8gwV5Zq'
    rases_7:
      email: "xxxxxxx@correo.policia.gov.co"
      name: "RASES_7"
      password: "$2b$12$TZuofnCnsC7mWOZN0k9n8ubPeHqiibHvnRkjNmyR7MHeskSL5lGb6" # Hash bcrypt para 'aAh1Uvc283x8'
    rases_8:
      email: "xxxxxxx@correo.policia.gov.co"
      name: "RASES_8"
      password: "$2b$12$wAV6uIHVTY0EqTZsLoIrFu45Qygsd4oTZVsVuUFAmjXyPYqx4/kMy" # Hash bcrypt para '3wP5LS3A87J9'
    hocen:
      email: "xxxxxxx@correo.policia.gov.co"
      name: "HOCEN"
      password: "$2b$12$s8XXSL.clhjG9RDEkySqKOGxRJr1Vp3qsgCXyb4N14tfFMAS/Vr36" # Hash bcrypt para 'A193RFmPJx16'


cookie:
  expiry_days: 120
  key: "dignidad_del_vencido"
  name: "sipqr2s_auth_cookie"
preauthorized:
  emails: []